[theme]
name = "solarized-light"

[icons]
name = "awesome5"

[[block]]
block = "focused_window"
max_width = 100
show_marks = "all"

# [[block]]
# block = "disk_space"
# path = "/"
# alias = "/"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0
# format="{icon} {used}/{total}"

# [[block]]
# block = "disk_space"
# path = "/home"
# alias = "/home"
# info_type = "available"
# unit = "GB"
# interval = 20
# warning = 20.0
# alert = 10.0

# [[block]]
# block = "notify"


[[block]]
block = "music"
# player = "chromium.instance1767328"
buttons = ["prev", "play", "next"]
max_width = 40
format = "{combo}"

[block.theme_overrides]
idle_bg = "#002b36" # base03
idle_fg = "#93a1a1" # base1
info_bg = "#268bd2" # blue
info_fg = "#002b36" # base03
good_bg = "#859900" # green
good_fg = "#002b36" # base03
warning_bg = "#b58900" # yellow
warning_fg = "#002b36" # base03
critical_bg = "#dc322f" # red
critical_fg = "#002b36" # base03


[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used}"
format_swap = "{swap_used_percents}"

[[block]]
block = "net"
device = "wlo1"
format = "{ssid} {signal_strength} {bitrate;M}"
interval = 10

[[block]]
block = "cpu"
format = "{utilization} {frequency}"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
